services:
  app.service.institution:
    class: AppProva\Domain\Service\InstitutionService
    arguments:
      - '@app.repository.institution'
      - '@logger'

  app.service.course:
    class: AppProva\Domain\Service\CourseService
    arguments:
      - '@app.repository.course'
      - '@logger'

  app.service.score:
    class: AppProva\Domain\Service\ScoreService
    arguments:
      - '@app.repository.score'
      - '@logger'