services:
    app.repository.institution:
        class: AppBundle\Repository\InstitutionRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppProva\Domain\Entity\Institution