AppProva\Domain\Entity\Score:
  type: entity
  table: null
  repositoryClass: AppBundle\Repository\ScoreRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    courseGeneralScore:
      type: integer
      length: 3
    courseStudentAvgScore:
      type: integer
      length: 3
    createdAt:
      type: datetime
    updatedAt:
      type: datetime
      nullable: true
  lifecycleCallbacks:
    prePersist: [ forgeCreatedAt ]
    preUpdate: [ forgeUpdatedAt ]
  manyToOne:
    institution:
      targetEntity: AppProva\Domain\Entity\Institution
      inversedBy: score
      joinColumn:
        name: institution_id
        referencedColumnName: id
        onDelete: CASCADE
    course:
      targetEntity: AppProva\Domain\Entity\Course
      inversedBy: score
      joinColumn:
        name: course_id
        referencedColumnName: id
        onDelete: CASCADE